name: Delete Old Messages

on:
  schedule:
    - cron: "0 0 * * *" # Codziennie o północy UTC

jobs:
  delete_old_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Delete Old Messages
        run: |
          FILE=messages.json
          if [ -f "$FILE" ]; then
            jq 'map(select((now - (.timestamp | fromdateiso8601)) < 86400))' $FILE > temp.json
            mv temp.json $FILE
          fi

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add messages.json
          git commit -m "Usunięto stare wiadomości" || echo "Nic do zcommitywania"
          git push
